/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kitten.glb -o src/components/kitten.jsx -k -K -r public 
Author: SmugglersStudio (https://sketchfab.com/SmugglersStudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kitten-monk-23431a450c8a47f6a6dc76ae4f672f16
Title: Kitten Monk
*/

import React, { useEffect, useRef } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations,Text } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function KittenGame({
    name="Player",
    animation="idle",
  ...props
}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/kitten.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

   useEffect(() => {
        //  console.log('Rick Loaded Materials:', materials);
        actions[animation]?.reset().fadeIn(0.24).play();
        return () => actions?.[animation]?.fadeOut(0.24);
      }, [animation]);

       const textRef = useRef();
          
        useFrame(({ camera }) => {
      
          if (textRef.current) {
      
            textRef.current.lookAt(camera.position);
      
          }
      
        });

  return (
    <group ref={group} {...props} dispose={null}>
         <group ref={textRef}>
        
        <Text
            position-y={3.8}
            fontSize={0.5}
            anchorX="center"
            anchorY="middle"
            font="fonts/PaytoneOne-Regular.ttf"
          >
            {name}
            <meshBasicMaterial color="white" />
          </Text>
          <Text
            position-y={3.78}
            position-x={0.02}
            position-z={-0.02}
            fontSize={0.5}
            anchorX="center"
            anchorY="middle"
            font="fonts/PaytoneOne-Regular.ttf"
          >
            {name}
        
            <meshBasicMaterial color="black" />
        
          </Text>
        
        </group>

      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.443}>
          <group name="kitten-monkfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="root" position={[1.402, -3.54, 0.993]} rotation={[-1.582, -0.077, -1.552]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_41" position={[1.402, -3.54, 0.993]} rotation={[-1.582, -0.077, -1.552]} />
                    <skinnedMesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials['kitten-2']} skeleton={nodes.Object_42.skeleton} />
                  </group>
                </group>
                <group name="retop" position={[1.402, -3.54, 0.993]} rotation={[-1.582, -0.077, -1.552]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/kitten.glb',"draco/gltf/");
