/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spongebobfish.glb -o src/components/Spongebobfish.jsx -k -K -r public 
Author: hodart (https://sketchfab.com/hodart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spongebob-male-fish-d2d0b64891ba4f2da3561300f3d6356e
Title: SpongeBob Male Fish
*/
import React, { useRef,useEffect } from 'react';
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, Text } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Spongebobfish({
  animation="Slasa Dancing",
  color = "yellow",
  name="Player",
  ...props
  }) {
  const group = useRef();
  const { scene, animations } = useGLTF('/models/spongebobfish.glb',"draco/gltf/");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  	
  useEffect(() => {
    // console.log('Loaded Materials:', materials);
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);
 
  const textRef = useRef();

  useFrame(({ camera }) => {
    if (textRef.current) {
      textRef.current.lookAt(camera.position);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group ref={textRef}>
      <Text
          position-y={3.8}
          fontSize={0.5}
          anchorX="center"
          anchorY="middle"
          font="fonts/PaytoneOne-Regular.ttf"
        >
          {name}
          <meshBasicMaterial color="white" />
        </Text>
        <Text
          position-y={3.78}
          position-x={0.02}
          position-z={-0.02}
          fontSize={0.5}
          anchorX="center"
          anchorY="middle"
          font="fonts/PaytoneOne-Regular.ttf"
        >
          {name}
          <meshBasicMaterial color="black" />
        </Text>
      </group>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.837}>
          <group name="7819c780424e42cbb6debbe9d1a04ac4fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="hair_04" />
                <group name="eyes" />
                <group name="mustache" />
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_8">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_10" />
                    <group name="Object_12" />
                    <group name="Object_14" />
                    <group name="Object_41" />
                    <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.hair_04} skeleton={nodes.Object_11.skeleton} />
                    <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.material} skeleton={nodes.Object_13.skeleton} />
                    <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.mustache} skeleton={nodes.Object_15.skeleton} />
                    <skinnedMesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.shorts} skeleton={nodes.Object_42.skeleton} />
                    <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.body} skeleton={nodes.Object_43.skeleton} />
                    <skinnedMesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.shirt} skeleton={nodes.Object_44.skeleton} />
                  </group>
                </group>
                <group name="body" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/spongebobfish.glb',"draco/gltf/");
