/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rick.glb -o src/components/Rick.jsx -k -K -r public 
Author: DavidA3D (https://sketchfab.com/DavidA3D)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/rick-rick-and-morty-animation-test-9a1346e36d2f47289fc37b5d87335e99
Title: Rick (Rick and Morty) - Animation Test
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Rick({
  animation="Armature|Clip1Bod",
  ...props
}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/rick.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
     console.log('Rick Loaded Materials:', materials);
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);
 

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="RickFullfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Point001" position={[168.6, 45.556, -253.403]} scale={100}>
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group name="Point" position={[0, 132.168, 168.489]} scale={100}>
                  <group name="Object_8" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_9" />
                  </group>
                </group>
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_11">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_119" scale={100} />
                    <skinnedMesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.Material} skeleton={nodes.Object_120.skeleton} morphTargetDictionary={nodes.Object_120.morphTargetDictionary} morphTargetInfluences={nodes.Object_120.morphTargetInfluences} />
                  </group>
                </group>
                <group name="Cube" scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/rick.glb',"draco/gltf/")
